@startuml

cloud Github

package "Front End" {
  [Nginx]
}

package "Back End" {
  Nginx --> [Gunicorn]
}

package "Database" { 
Gunicorn --> [PostgreSQL]
}

Github ..> Gunicorn

@enduml