@startuml
package "Front End" {
  [Nginx]
}

package "Back End" {
  Nginx --> [Gunicorn]
}

package "Back End 2" {
  Nginx --> [Gunicorn2]
}

package "Database" { 
Gunicorn --> [PostgreSQL]
Gunicorn2 --> [PostgreSQL]
}
@enduml